version: '3.8'

services:
  db:
    image: postgres:15
    container_name: lab_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pet_store
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
      - ./mock_data:/mock_data 